#!/bin/bash
#
# Copyright (C) 2014 Trevor Drake
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Android ( AOSP ) Development Environment Setup script for *buntu 14.04
# 
# This is a lightweight script performs the following setup tasks
#
# Set ccache related environment variables if they are not already defined
# Set OUT_DIR_COMMON_BASE base environment variable if it is not already defined
# Create and load udev rules for common devices if non exist.
# Download the latest version of the repo tool. 
# Install the minimum packages required to build the master branch
#
# JDK INFO: 
# The master branch now uses Java 7 and is compatible with OpenJDK.
# 
# Building other branches:
# See http://source.android.com/source/initializing.html for information
#
# Usage :
# init_android_dev_master.sh <CCACHE_DIR> <OUT_DIR_COMMON_BASE>

LOCAL_CCACHE_DIR=$1
LOCAL_OUT_DIR_COMMON_BASE=$2

LOCAL_REPO_CMD=/usr/local/bin/repo
LOCAL_UDEV_RULES=/etc/udev/rules.d/51-android.rules

if test ! -z $CCACHE_DIR ; then 
	# unset 
	unset LOCAL_CCACHE_DIR
	echo "CCACHE_DIR Already Set Externally"
fi

if test ! -z $LOCAL_CCACHE_DIR  ; then
	echo "Setting up CCACHE"
	# only export use_ccache if we don't already
	test -z $USE_CCACHE && echo "export USE_CCACHE=1" >> $HOME/.bashrc 
	test -z $CCACHE_DIR && echo "export CCACHE_DIR=$LOCAL_CCACHE_DIR" >> $HOME/.bashrc 
fi 

if test ! -z $OUT_DIR_COMMON_BASE ; then 
	unset LOCAL_OUT_DIR_COMMON_BASE
	echo "OUT_DIR_COMMON_BASE already set externally"
else
	test ! -z $LOCAL_OUT_DIR_COMMON_BASE && echo "export OUT_DIR_COMMON_BASE=$LOCAL_OUT_DIR_COMMON_BASE" >> $HOME/.bashrc 
fi


# download the latest version of the repo tool. This will overwrite any existing version
CURRENT_REPO_CMD=`which repo`
if test ! -z $CURRENT_REPO_CMD ; then
	LOCAL_REPO_CMD=$CURRENT_REPO_CMD
	echo "Updateing existing repo [ $LOCAL_REPO_CMD ]"
else
	echo "Downloading repo"
fi
sudo sh -c "curl -s http://commondatastorage.googleapis.com/git-repo-downloads/repo > $LOCAL_REPO_CMD"
sudo chmod 755 $LOCAL_REPO_CMD

# 
if test -f $LOCAL_UDEV_RULES  ; then 
	echo "$LOCAL_UDEV_RULES already exists"
else
	echo "Creating udev [ $LOCAL_UDEV_RULES ] rules for known android devices"
	# Create a 51-android.rules for udev - using all known vendors
	sudo sh -c "echo '
# /etc/udev/rules.d/51-android.rules - generated by init_android_dev.sh
# sudo udevadm control --reload-rules

# Acer - Vendorid 0x0502 
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0502\", MODE=\"0666\", GROUP=\"plugdev\"
# Archos - Vendorid 0xe79
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0e79\", MODE=\"0666\", GROUP=\"plugdev\"
# Asus - Vendorid 0x0b05 
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0b05\", MODE=\"0666\", GROUP=\"plugdev\"
# Dell - Vendorid 0x413c
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"413c\", MODE=\"0666\", GROUP=\"plugdev\"
# Foxconn - Vendorid 0x0489
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0489\", MODE=\"0666\", GROUP=\"plugdev\"
# Fujitsu/Fujitsu Toshiba - Vendorid 0x04c5
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"04c5\", MODE=\"0666\", GROUP=\"plugdev\"
# Garmin-Asus - Vendorid 0x091e
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"091e\", MODE=\"0666\", GROUP=\"plugdev\"
# Google - Vendorid 0x18d1
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"18d1\", MODE=\"0666\", GROUP=\"plugdev\"
# Hisense - Vendorid 0x109b
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"109b\", MODE=\"0666\", GROUP=\"plugdev\"
# HTC - Vendorid 0x0bb4
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0bb4\", MODE=\"0666\", GROUP=\"plugdev\"
# Huawei - Vendorid 0x12d1
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"12d1\", MODE=\"0666\", GROUP=\"plugdev\"
# Intel - Vendorid 0x8087
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"8087\", MODE=\"0666\", GROUP=\"plugdev\"
# K-Touch - Vendorid 0x24e3
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"24e3\", MODE=\"0666\", GROUP=\"plugdev\"
# KT Tech - Vendorid 0x2116
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"2116\", MODE=\"0666\", GROUP=\"plugdev\"
# Kyocera - Vendorid 0x-482
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0482\", MODE=\"0666\", GROUP=\"plugdev\"
# Lab126 ( Amazon )   - Vendorid 0x1949
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"1949\", MODE=\"0666\", GROUP=\"plugdev\"
# Lenovo  - Vendorid 0x17ef
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"17ef\", MODE=\"0666\", GROUP=\"plugdev\"
# Lenovo Mobile  - Vendorid 0x2006
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"2006\", MODE=\"0666\", GROUP=\"plugdev\"
# LG - Vendorid 0x1004
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"1004\", MODE=\"0666\", GROUP=\"plugdev\"
# Motorola - Vendorid 0x22b8
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"22b8\", MODE=\"0666\", GROUP=\"plugdev\"
# NEC - Vendorid 0x0409
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0409\", MODE=\"0666\", GROUP=\"plugdev\"
# Nook - Vendorid 0x2080
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"2080\", MODE=\"0666\", GROUP=\"plugdev\"
# Nvida - Vendorid 0x0955
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0955\", MODE=\"0666\", GROUP=\"plugdev\"
# OTGV - Vendorid 0x2257
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"2257\", MODE=\"0666\", GROUP=\"plugdev\"
# Pantech - Vendorid 0x10a9
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"10a9\", MODE=\"0666\", GROUP=\"plugdev\"
# Pegatron - Vendorid 0x1d4f
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"1d4d\", MODE=\"0666\", GROUP=\"plugdev\"
# Philips - Vendorid 0x0471
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0471\", MODE=\"0666\", GROUP=\"plugdev\"
# Panasonic Mobile Communications -Sierra - Vendorid 0x04da
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"04da\", MODE=\"0666\", GROUP=\"plugdev\"
# Qualcomm - Vendorid 0x05c6
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"05c6\", MODE=\"0666\", GROUP=\"plugdev\"
# SK Telesys - Vendorid 0x5c6
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"1f53\", MODE=\"0666\", GROUP=\"plugdev\"
# Samsung - Vendorid 0x04e8
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"04e8\", MODE=\"0666\", GROUP=\"plugdev\"
# Sharp - Vendorid 0x04dd
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"04dd\", MODE=\"0666\", GROUP=\"plugdev\"
# Sony - Vendorid 0x054c
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"054c\", MODE=\"0666\", GROUP=\"plugdev\"
# Sony Ericsson - Vendorid 0x0fce
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0fce\", MODE=\"0666\", GROUP=\"plugdev\"
# Teleepoch - Vendorid 0x2340
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"2340\", MODE=\"0666\", GROUP=\"plugdev\"
# Texas Instruments - Vendorid 0x0451
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0451\", MODE=\"0666\", GROUP=\"plugdev\"
# Toshiba - Vendorid 0x0930
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0930\", MODE=\"0666\", GROUP=\"plugdev\"
# ZTE - Vendorid 0x19d2
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"19d2\", MODE=\"0666\", GROUP=\"plugdev\"
# Rokchip 3066 Mk809ii - Vendorid 0x2207
SUBSYSTEM==\"usb\", ATTR{idVendor}==\"2207\", MODE=\"0666\", GROUP=\"plugdev\"' \
> $LOCAL_UDEV_RULES"

	# Restart udev so we can get busy straight away
	echo "Reloading udev rules"
	sudo udevadm control --reload-rules
fi

# Test for apt-fast 
APT_GET=`which apt-fast > /dev/null && which apt-fast || which apt-get`
echo "Using `basename $APT_GET`"

APT_GET_YES="--yes --force-yes"
APT_GET_INSTALL="sudo $APT_GET $APT_GET_YES install"
echo "$APT_GET_INSTALL"

$APT_GET_INSTALL openjdk-7-jdk:amd64

$APT_GET_INSTALL git:amd64 gnupg:amd64 flex:amd64 bison:amd64 gperf:amd64 zip:amd64 curl:amd64 
$APT_GET_INSTALL x11proto-core-dev:amd64 python-markdown:amd64 libxml2-utils:amd64 xsltproc:amd64 

$APT_GET_INSTALL libncurses5-dev:i386 libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 zlib1g-dev:i386 

$APT_GET_INSTALL make:amd64 g++-multilib:amd64 


